### ISSUE TITLE
Update BOM / ease procuring of stepper motors

### ISSUE THREAD

**Issue by dirkx** [bdring/midTbot_esp32#10]
The currently specced/linked stepper motor [link](https://www.omc-stepperonline.com/nema-14-stepper-motor/nema-14-bipolar-18deg-5ncm-708ozin-04a-10v-35x35x20mm-4-wires-14hs08-0404s.html) in the [bom](https://github.com/bdring/midTbot_esp32/blob/master/Docs/mechanical_BOM.md) has a fairly short axis (12.5mm length).

Actual round axis length can be up to 22mm to still clear the left/right feet. 

So would suggest updating the BOM to allow up to 20.8mm of shaft length. 

And perhaps clarify that the mentioned 20mm body/enclosure size is not that critical. 

As that means there are many more stepper motor suppliers suddenly.

**Comment by bdring** [comment]
The stepper motor must be a NEMA14 with 5mm shaft. 

The height of the body of the motor must be 20mm or less to fit the standard cover. A taller motor is fine if you don't use a cover or design a deeper one.

The motor shaft on the one listed in the BOM is rather short. I can be up to about 20mm long.

I have linked this issue to the BOM.

Closing issue.

**Comment by bdring** [comment]
[Here is an amazon link for a motor that should work.](https://www.amazon.com/gp/product/B00PNEPQ8E/ref=ppx_od_dt_b_slice_asin_title?ie=UTF8&psc=1)
