### ISSUE TITLE
No ESP32 chip listed in the BOM

### ISSUE THREAD

**Issue by dwightmulcahy** [bdring/midTbot_esp32#14]
Docs/mechanical_BOM.md does not list the ESP32 chip to get.

here is a link to ESP32 Dev:
https://www.amazon.com/HiLetgo-ESP-WROOM-32-Development-Microcontroller-Integrated/dp/B0718T232Z

~~Or this one for two:
https://www.amazon.com/MELIFE-Development-Dual-Mode-Microcontroller-Integrated/dp/B07Q576VWZ~~

**Comment by bdring** [comment]
Do not get the second one. It has the wrong number of pins.

It needs to be 19x2 with a pin width space of 0.9". Do not get the 15x2 version or the 19x2 1.0" width version.

**Comment by dwightmulcahy** [comment]
Ugh, thanks... 

the specs on these seem hard to find but this one seems to meet the needs, 19x2 and ~0.89" pin spacing:
https://www.amazon.com/KeeYees-Development-Bluetooth-Microcontroller-ESP-WROOM-32/dp/B07QCP2451

**Comment by bdring** [comment]
Most of my boards support the (2) widths of the 19x2 types.  I'll be adding this to the next rev of the PCB. I'll be ordering and testing it before I post it.

![image](https://user-images.githubusercontent.com/189677/64058083-66507980-cb6b-11e9-979c-bacf057870c5.png)

**Comment by dwightmulcahy** [comment]
nice.  I bought one of the v1 boards that you had...

**Comment by dwightmulcahy** [comment]
ended up getting this one: https://www.amazon.com/gp/product/B0718T232Z

closing this issue as the PCB/BOM.md lists the need for an ESP32 Dev Kit (0.9" Wide Type).
