### ISSUE TITLE
Feature/improvement: through the hole capacitors

### ISSUE THREAD

**Issue by dirkx** [bdring/midTbot_esp32#6]
Would be nice to also have hole-pads for the 4 SMD capacitors. So you have the option.

Probably not practical for the SD slot - as those are (too) hard to get in through the hole versions.

**Comment by bdring** [comment]
These days most people are getting pretty comfortable hand soldering things like 1206 and 0805 caps. I don't want to change those parts.

The SD card is a PITA, but there are not too many options. On my first test controller, I used a standard SD card module. I don't know if there is a way to fit that and still make the card accessible.

![image](https://user-images.githubusercontent.com/189677/63061120-be278900-beb9-11e9-8c2f-dedaf3af9249.png)

**Comment by bdring** [comment]
Checked: There is no good location for the standard micro SD card module.

![image](https://user-images.githubusercontent.com/189677/63231446-79fdf680-c1e1-11e9-8cca-1cd016d645ec.png)

closing issue
